修复协程函数执行 #301 #332
Ourpalm/ILRuntime pull request #453
Opened 2021-01-19 06:47 UTC by hproof

我不确定是否会引起其它问题， 但该修改可以解决协程无法正常执行的问题。

在协程函数中， 例如：
static IEnumerator func1()
{
         foreach (var x in GetDatas())
        {
              yield return null;    // 此处会生成 leave.s 指令,  之前的解析器中会执行 Fault 代码， 导致提前执行该协程的析构函数， 破坏了协程的执行

2021-01-21 09:52 UTC, hproof commented
例如  List.Sort( (a,b) => ... ); ， 静态分析 可用于查找 哪个函数创建了哪些 delegate

2021-01-25 11:45 UTC, hproof commented
CLRMethod.Invoke 执行后 invocationParam 没有释放

2021-02-23 03:28 UTC, liiir1985 requested changes
一个PR中不应该混入多个feature或者bug fix，否则没有办法合并的，请将修改内容拆成独立的PR

2021-12-03 11:56 UTC, liiir1985 commented
Fixed in ead5fb6eec7ed5097c52ef5998da5acdae242567

2021-12-03 11:56 UTC, closed without merging