递归prewarm
Ourpalm/ILRuntime pull request #474
Opened 2021-03-09 04:55 UTC by qiulirui

以递归方式prewarm当前方法，以及所有子调用。提高prewarm的准确性。已知缺陷：遇到CLRMethod（跨域调用）就会打断递归。

2021-03-09 07:44 UTC, liiir1985 requested changes

2021-03-09 07:44 UTC, liiir1985 commented on ILRuntime/CLR/Method/ILMethod.cs
> +        public void Prewarm(HashSet<ILMethod> alreadyPrewarmed)
HashSet参数作为是否递归的条件容易让人困惑，可以用bool recursive = false作为参数，然后递归时内部自己定义这个HashSet

2021-03-09 07:44 UTC, liiir1985 commented on ILRuntime/CLR/Method/ILMethod.cs
> +        void InitCodeBody(HashSet<ILMethod> alreadyPrewarmed = null)
ILMethod等内部底层方法不应加入不相关的参数，一方面多一个参数和判断影响性能
另一方面污染该方法的作用

建议参考CLRBinding的CrawlAppdomain, 通过取到Instruction的Opcode就可以得到下一层递归

2021-03-10 04:25 UTC, qiulirui commented on ILRuntime/CLR/Method/ILMethod.cs
> +        void InitCodeBody(HashSet<ILMethod> alreadyPrewarmed = null)
好的，我学习一下再改

2021-03-26 07:38 UTC, liiir1985 approved these changes

2021-03-26 07:38 UTC, merged